---
title: "SNR 690 — Contemporary Approaches to Quantitative Methods"
author: "Dr. Alejandro Molina-Moctezuma"
format: html
number-sections: false
---

Welcome to the course materials for SNR 690.

Instructor: Dr. Alejandro Molina-Moctezuma\
Credits: 3\
Format: 2 sessions per week (75 minutes each)\
Semester: Spring 2026

This book contains the syllabus, weekly readings, assignments, projects, papers, code notebooks, and everything we do in this class. This website will be a collaborative process.

We will be updating this landing page as the course goes on!

## Resources

*this section will be updated regularly* 
If you are struggling with R or RStudio, check out these resources: 

Wickham @wickhamDataScienceImport2023 here: [https://r4ds.had.co.nz/](https://r4ds.had.co.nz/) 

    
Data science in R: A gentle introduction [https://bookdown.org/jgscott/DSGI/](https://bookdown.org/jgscott/DSGI/)

And check the materials of my SNR 610 course here: 
[https://moctezumaii.github.io/SNR610/](https://moctezumaii.github.io/SNR610/) 


Where you can access info regarding R and models.

## Links and inforrmation:

[Syllabus](/syllabus.html)

[What are we doing this week?](/slides/slide-Week01.html "Week 1 info!") –\> Here you will fin what papers to read, and have an idea of what each class is going to look like!

Contact Information and office hours: Find me in my office ANRB 474! 😃